using System.Text.RegularExpressions;
using Microsoft.Data.Sqlite;

namespace Hades.Core.Memory;

/// <summary>One ranked hit from <see cref="MemoryIndex.Search"/>.</summary>
public sealed record MemorySearchHit
{
    /// <summary>The source document's plain basename, e.g. "conventions.md" - so a caller can cite
    /// exactly where guidance came from.</summary>
    public required string Name { get; init; }

    /// <summary>A short excerpt of the matching text, generated by SQLite FTS5's own snippet()
    /// function.</summary>
    public required string Excerpt { get; init; }

    /// <summary>Higher is more relevant. This is FTS5's own bm25() score negated: SQLite's raw
    /// bm25() returns a "cost" where a MORE NEGATIVE number is a better match (so that FTS5's
    /// built-in `ORDER BY rank` sorts best-first in ascending order); negating it gives callers
    /// the more intuitive "bigger number, better match" convention instead.</summary>
    public required double Score { get; init; }
}

/// <summary>
/// A ranked, full-text search index over AUTHORED memory documents - the direct children of
/// memory/ (see <see cref="MemoryStore.KnownDocuments"/>), never memory/proposals/, whose pending,
/// unaccepted content is not citable "guidance" the way an authored document is. Entirely DERIVED:
/// every row here is reconstructible from the *.md files on disk via
/// <see cref="SyncFromDirectory"/>, so deleting this database and reopening it costs nothing but a
/// resync - the same guarantee graph.db makes for the knowledge graph (see GraphSchema's class doc
/// comment) - see this class's own "delete the database and reopen" test for the proof.
///
/// Backed by SQLite's FTS5 extension for ranked (BM25) search, replacing the previous
/// implementation's naive substring OR-matching with no scoring at all. Query text is never
/// trusted: see <see cref="Search"/> for how caller-authored text is kept from ever being parsed
/// as FTS5 query syntax (AND/OR/NOT, NEAR(...), prefix "*", column filters, phrase quoting) - the
/// same discipline <see cref="Graph.GraphDatabase"/> applies to SQL LIKE wildcards
/// (see its EscapeLikeWildcards), extended here to a second, independently hostile query grammar.
/// </summary>
public sealed class MemoryIndex : IDisposable
{
    readonly SqliteConnection _connection;

    MemoryIndex(SqliteConnection connection) => _connection = connection;

    public static MemoryIndex Open(string databasePath)
    {
        var directory = Path.GetDirectoryName(databasePath);
        if (!string.IsNullOrEmpty(directory)) Directory.CreateDirectory(directory);

        // Pooling = false: see Graph.GraphDatabase.Open's comment on the identical block - a pooled
        // connection keeps the file handle open past Dispose, which Windows will not let you delete.
        var connection = new SqliteConnection(new SqliteConnectionStringBuilder
        {
            DataSource = databasePath,
            Mode = SqliteOpenMode.ReadWriteCreate,
            Pooling = false,
        }.ToString());

        try
        {
            connection.Open();

            // See Graph.GraphDatabase.Open's identical block: the RESULTING mode must be read back
            // and checked, not assumed - a refused WAL conversion (another connection holding the
            // file, or a filesystem that does not support it) must be visible, not silently eaten.
            using (var journalMode = connection.CreateCommand())
            {
                journalMode.CommandText = "PRAGMA journal_mode = WAL;";
                var resulting = journalMode.ExecuteScalar() as string;

                if (!string.Equals(resulting, "wal", StringComparison.OrdinalIgnoreCase))
                {
                    throw new InvalidOperationException(
                        $"Could not put '{databasePath}' into WAL mode (it reports '{resulting}'). "
                        + "Another process may hold the database, or it may be on a filesystem "
                        + "that does not support WAL, such as a network share.");
                }
            }

            using (var synchronous = connection.CreateCommand())
            {
                synchronous.CommandText = "PRAGMA synchronous = NORMAL;";
                synchronous.ExecuteNonQuery();
            }

            EnsureSchema(connection);
        }
        catch
        {
            connection.Dispose();
            throw;
        }

        return new MemoryIndex(connection);
    }

    /// <summary>
    /// No migration machinery, unlike GraphSchema: this is the first and only shape memory_fts has
    /// ever had. The whole table is derived data (see this class's own doc comment), so if that
    /// shape ever needs to change, the fix is a DROP + CREATE against a fresh file, not an in-place
    /// ALTER - the same reasoning GraphSchema documents for the graph, just with no history yet to
    /// migrate FROM.
    ///
    /// `tokenchars '_'` keeps identifiers like "m_Health" one token rather than splitting on the
    /// underscore - FTS5's default unicode61 tokenizer treats '_' as a separator, which would
    /// silently index "m_Health" as two unrelated tokens ("m", "health"). Same "underscores are
    /// routine in Unity/C# identifiers" reasoning as <see cref="Graph.GraphDatabase.SearchByName"/>'s
    /// LIKE-escaping, independently necessary here because FTS5 tokenization and SQL LIKE are two
    /// unrelated mechanisms with two unrelated defaults to fight.
    /// </summary>
    static void EnsureSchema(SqliteConnection connection)
    {
        using var command = connection.CreateCommand();
        command.CommandText = """
            CREATE VIRTUAL TABLE IF NOT EXISTS memory_fts USING fts5(
                name UNINDEXED,
                body,
                tokenize = "unicode61 tokenchars '_'"
            );
            """;
        command.ExecuteNonQuery();
    }

    /// <summary>Upserts one document's content. An existing row for <paramref name="name"/> is
    /// replaced outright - delete then insert, since FTS5 has no natural ON CONFLICT target to
    /// upsert against - so calling this again for a name already indexed is how an edit on disk
    /// becomes visible to search.</summary>
    public void IndexDocument(string name, string body)
    {
        ArgumentNullException.ThrowIfNull(name);
        ArgumentNullException.ThrowIfNull(body);

        using var transaction = _connection.BeginTransaction();
        DeleteByName(transaction, name);
        InsertDocument(transaction, name, body);
        transaction.Commit();
    }

    /// <summary>Removes one document from the index - how a file deleted on disk stops appearing
    /// in results. A name not currently indexed is a silent no-op, not an error: the same
    /// "deleting what is already gone is fine" stance <see cref="Graph.GraphDatabase.DeleteNodesForPath"/>
    /// takes.</summary>
    public void RemoveDocument(string name)
    {
        ArgumentNullException.ThrowIfNull(name);

        using var transaction = _connection.BeginTransaction();
        DeleteByName(transaction, name);
        transaction.Commit();
    }

    /// <summary>
    /// Rebuilds the entire index from the *.md files directly inside <paramref name="memoryDir"/> -
    /// one level only, never memory/proposals/ (see this class's own doc comment for why). A full
    /// clear-then-reinsert, not an incremental diff: memory corpora are a handful of small files,
    /// so rescanning everything on every call costs nothing worth optimising away, and doing it
    /// this way is what makes the index provably derived rather than merely believed to be. A
    /// directory that does not exist yet - a project with no memory written at all - leaves the
    /// index empty rather than throwing.
    /// </summary>
    public void SyncFromDirectory(string memoryDir)
    {
        ArgumentNullException.ThrowIfNull(memoryDir);

        using var transaction = _connection.BeginTransaction();

        using (var clear = _connection.CreateCommand())
        {
            clear.Transaction = transaction;
            clear.CommandText = "DELETE FROM memory_fts;";
            clear.ExecuteNonQuery();
        }

        if (Directory.Exists(memoryDir))
        {
            // Not Directory.EnumerateFiles(memoryDir, "*.md"): that search pattern's case
            // sensitivity follows the underlying filesystem, case-SENSITIVE on Linux (unlike
            // Windows/macOS's usual defaults) - a document named e.g. "CAPS.MD" would silently
            // never be indexed, and so never found by Search, on Linux alone. Filtering in C# with
            // OrdinalIgnoreCase makes every platform behave the same, matching
            // MemoryStore.EnumerateMdFiles's identical fix.
            foreach (var path in Directory.EnumerateFiles(memoryDir)
                         .Where(p => Path.GetFileName(p).EndsWith(".md", StringComparison.OrdinalIgnoreCase))
                         .OrderBy(p => p, StringComparer.Ordinal))
            {
                var name = Path.GetFileName(path);
                // Indexed by Body, not RawText: a word in the frontmatter (last_reviewed: ...)
                // finding a document would be a coincidence of the YAML syntax, not the guidance
                // it holds.
                var body = MemoryFile.Parse(name, File.ReadAllText(path)).Body;
                InsertDocument(transaction, name, body);
            }
        }

        transaction.Commit();
    }

    /// <summary>
    /// Ranked full-text search over indexed document bodies. <paramref name="query"/> is free-form
    /// caller text, trusted with nothing: it is tokenized here in C# - letters, digits, and
    /// underscore only, the same character class FTS5 itself is configured to treat as a token (see
    /// <see cref="EnsureSchema"/>) - and every extracted token is rebuilt as its own quoted FTS5
    /// phrase before reaching SQLite. Because a token can, by construction, never contain a quote,
    /// a paren, an asterisk, or whitespace, none of it can ever be parsed as FTS5 query syntax -
    /// punctuation and keywords a caller did not intend as operators ("OR", "NEAR(", "*", a bare
    /// '"') come through as inert literal text, not query grammar. A query with no recognisable
    /// token at all (empty, whitespace, or pure punctuation) returns no results without even
    /// touching the database, the same answer an index with nothing in it gives.
    /// </summary>
    public IReadOnlyList<MemorySearchHit> Search(string query, int limit = 20)
    {
        ArgumentNullException.ThrowIfNull(query);

        var tokens = QueryTokenPattern.Matches(query).Select(m => m.Value).ToList();
        if (tokens.Count == 0) return [];

        var matchExpression = string.Join(" ", tokens.Select(t => $"\"{t}\""));

        using var command = _connection.CreateCommand();
        command.CommandText = """
            SELECT name, snippet(memory_fts, 1, '', '', '…', 16) AS excerpt, bm25(memory_fts) AS raw_score
            FROM memory_fts
            WHERE memory_fts MATCH $query
            ORDER BY raw_score ASC
            LIMIT $limit;
            """;
        command.Parameters.AddWithValue("$query", matchExpression);
        command.Parameters.AddWithValue("$limit", Math.Clamp(limit, 1, MaxResults));

        var results = new List<MemorySearchHit>();
        using var reader = command.ExecuteReader();
        while (reader.Read())
        {
            results.Add(new MemorySearchHit
            {
                Name = reader.GetString(0),
                Excerpt = reader.GetString(1),
                Score = -reader.GetDouble(2),
            });
        }

        return results;
    }

    /// <summary>Token characters accepted from caller query text - letters, digits, underscore.
    /// Matches <see cref="EnsureSchema"/>'s `tokenchars '_'` configuration exactly, and
    /// deliberately excludes every FTS5 syntax character (quotes, parens, *, :, the whitespace that
    /// separates operator keywords) by construction: a token extracted by this pattern can never
    /// itself need escaping, because none of FTS5's special characters can appear in one.</summary>
    static readonly Regex QueryTokenPattern = new(@"[\p{L}\p{N}_]+", RegexOptions.Compiled);

    /// <summary>Upper bound on <see cref="Search"/>'s <c>limit</c> regardless of what a caller
    /// passes - same token-budget reasoning as <see cref="Graph.GraphDatabase"/>'s MaxSearchLimit,
    /// just scaled down: a memory corpus is a handful of documents, not thousands of graph nodes.</summary>
    const int MaxResults = 200;

    void DeleteByName(SqliteTransaction transaction, string name)
    {
        using var command = _connection.CreateCommand();
        command.Transaction = transaction;
        command.CommandText = "DELETE FROM memory_fts WHERE name = $name;";
        command.Parameters.AddWithValue("$name", name);
        command.ExecuteNonQuery();
    }

    void InsertDocument(SqliteTransaction transaction, string name, string body)
    {
        using var command = _connection.CreateCommand();
        command.Transaction = transaction;
        command.CommandText = "INSERT INTO memory_fts (name, body) VALUES ($name, $body);";
        command.Parameters.AddWithValue("$name", name);
        command.Parameters.AddWithValue("$body", body);
        command.ExecuteNonQuery();
    }

    public void Dispose() => _connection.Dispose();
}
