using Hades.Core.Indexing;
using Hades.Core.Unity;
using YamlDotNet.Core;
using YamlDotNet.Core.Events;

namespace Hades.Core.Reading;

/// <summary>
/// Parses one named scene or prefab file on demand - the read-through half of Hades' two ways of
/// answering questions. Graph-served tools answer questions that span files, from the SQLite
/// index; this answers a question about ONE file the caller already named, by opening it. Nothing
/// here touches the graph or any other file, which is what keeps a single call cheap (about a
/// millisecond) and never stale.
///
/// Every failure mode below is deliberate, not an oversight: a tool taking a caller-supplied path
/// is exactly where directory traversal gets attempted, a file named by a stale graph lookup can
/// have been deleted since, and a file caught mid-write is indistinguishable from one that is
/// simply malformed until it is actually parsed.
/// </summary>
public static class ReadThrough
{
    /// <summary>
    /// Resolves a caller-supplied, project-relative path to an absolute one, refusing anything
    /// that would read outside the project's scan roots (<see cref="ProjectWalker.ResolveScanRoots"/>
    /// - Assets/, Packages/, and any local "file:" package).
    ///
    /// Applies the same rigour as <see cref="Storage.AppPaths.ProjectDir"/>, whose three checks
    /// (null/blank, single-segment, strict-containment via <see cref="Path.GetFullPath"/>) were
    /// each proven necessary by ablation there. The equivalent here is: reject null/blank up
    /// front; reject anything already rooted, because <see cref="Path.Combine(string, string)"/>
    /// silently IGNORES its first argument when the second is rooted, so resolving a caller's
    /// absolute path against a scan root the ordinary way would hand back that path completely
    /// unchecked; then require the lexically resolved path to be a STRICT child of the matched
    /// root. That last check alone is still not enough, because <see cref="Path.GetFullPath(string)"/>
    /// is purely lexical and never touches the filesystem - a symlink planted inside a scan root
    /// (say, "Assets/Evil" pointing outside the project) would pass a string-prefix check while
    /// physically reading from wherever the link leads. The final walk resolves every symlink on
    /// the way down and re-checks containment after each one.
    ///
    /// Deliberately NOT the same code path as <see cref="Observation.ProjectSweeper.ToAbsolute"/>:
    /// that helper trusts its input, because it only ever runs on paths the indexer itself
    /// generated by walking the disk. This one runs on whatever a caller sends, so it does not
    /// get to make that assumption.
    /// </summary>
    public static string ResolveAssetPath(string projectRoot, string? relativePath)
    {
        if (string.IsNullOrWhiteSpace(relativePath))
        {
            throw new ArgumentException("Asset path must not be null or blank.", nameof(relativePath));
        }

        if (Path.IsPathRooted(relativePath))
        {
            throw new ArgumentException(
                $"'{relativePath}' must be project-relative (e.g. \"Assets/Prefabs/Enemy.prefab\"), "
                + "not an absolute path.",
                nameof(relativePath));
        }

        var scanRootWarnings = new List<string>();
        var roots = ProjectWalker.ResolveScanRoots(projectRoot, scanRootWarnings);

        // Longest prefix wins, exactly as ProjectSweeper.ToAbsolute does: prefixes nest (the
        // in-project "Packages" root is a textual prefix of a local package's
        // "Packages/com.example.thing" root), so taking the first match could resolve a package
        // file against the wrong root entirely.
        ScanRoot? matched = null;
        foreach (var root in roots)
        {
            var prefix = root.PathPrefix + "/";
            if (!relativePath.StartsWith(prefix, StringComparison.Ordinal)) continue;
            if (matched is null || root.PathPrefix.Length > matched.Value.PathPrefix.Length) matched = root;
        }

        if (matched is null)
        {
            throw new ArgumentException(
                $"'{relativePath}' is not under any of this project's scan roots (Assets/, "
                + "Packages/, or a local package). It must be project-relative, exactly as "
                + "search_by_name returns it.",
                nameof(relativePath));
        }

        var scanRoot = matched.Value;
        var rootAbsolute = Path.GetFullPath(scanRoot.AbsolutePath);
        var suffix = relativePath[(scanRoot.PathPrefix.Length + 1)..].Replace('/', Path.DirectorySeparatorChar);
        var candidate = Path.GetFullPath(Path.Combine(rootAbsolute, suffix));

        if (candidate.Length <= rootAbsolute.Length
            || !candidate.StartsWith(rootAbsolute + Path.DirectorySeparatorChar, StringComparison.Ordinal))
        {
            throw new ArgumentException($"'{relativePath}' resolves outside the project.", nameof(relativePath));
        }

        if (EscapesRootViaSymlink(rootAbsolute, candidate))
        {
            throw new ArgumentException(
                $"'{relativePath}' passes through a symlink that leads outside the project.",
                nameof(relativePath));
        }

        return candidate;
    }

    /// <summary>
    /// Parses the scene or prefab at <paramref name="relativePath"/> into its GameObject
    /// hierarchy. One renderer for both asset kinds - a scene and a prefab are the same YAML
    /// format, so nothing here distinguishes them beyond the file extension the caller supplied.
    /// </summary>
    /// <exception cref="ArgumentException">The path escapes the project's scan roots.</exception>
    /// <exception cref="FileNotFoundException">The file is no longer on disk.</exception>
    /// <exception cref="InvalidDataException">
    /// The file is not text Unity YAML, or does not parse cleanly all the way through.
    /// </exception>
    /// <exception cref="NotSupportedException">
    /// The file uses the legacy pre-2018.3 "Prefab:" format.
    /// </exception>
    public static AssetHierarchy GetHierarchy(string projectRoot, string relativePath)
    {
        var content = LoadValidatedContent(projectRoot, relativePath);
        var objects = UnityYamlReader.Read(content, relativePath);

        // The pre-2018.3 "Prefab:" format that PrefabInstanceReader already recognises and skips
        // (see its DeclaredTypeName check) marks the whole asset as legacy, not just one object.
        if (objects.Any(o => o.DeclaredTypeName == "Prefab"))
        {
            throw new NotSupportedException(
                $"'{relativePath}' uses the legacy pre-2018.3 'Prefab:' format, which Hades does "
                + "not read through. This is expected only for third-party assets shipped years "
                + "ago and never re-saved by a modern Unity version.");
        }

        return BuildHierarchy(relativePath, objects);
    }

    /// <summary>
    /// Every component attached to one GameObject - Transform included, since this tool's whole
    /// purpose is a complete inventory (unlike <see cref="HierarchyNode.Components"/>, which
    /// omits it because a node's position in the tree already represents it). Order matches
    /// <c>m_Component.component</c>'s own document order, which is Unity's own Inspector order.
    /// No graph involved: a MonoBehaviour's script identity is only its raw guid here (see
    /// <see cref="ComponentSummary.ScriptGuid"/>) - resolving it is component_get_all's job, one
    /// layer up.
    ///
    /// <paramref name="gameObjectFileId"/> accepts either fileId a caller could plausibly have in
    /// hand: the GameObject document's own, or its Transform's. The two are NOT interchangeable
    /// bookkeeping - <see cref="BuildHierarchy"/> keys a "GameObject"-kind <see cref="HierarchyNode"/>
    /// by its TRANSFORM's fileId (the tree is built by walking Transforms, via m_Father), so that
    /// is what prefab_get_contents / scene_get_hierarchy actually report for one. Confirmed against
    /// the real Hades-Unity-Client corpus: every real prefab's GameObject-kind node fileId is its
    /// Transform's, never the GameObject's own. Rejecting it and requiring the GameObject's own
    /// fileId instead would break the exact chain this tool exists for - "call prefab_get_contents,
    /// then feed a node's fileId to component_get_all".
    /// </summary>
    /// <exception cref="ArgumentException">
    /// The path escapes the project's scan roots, no object with <paramref name="gameObjectFileId"/>
    /// exists in the file, or it exists but is not a GameObject or its Transform (for example, a
    /// component's own fileId, or a nested/variant prefab instance's placeholder - resolving into a
    /// DIFFERENT file's GameObjects is cross-file work this deliberately does not do).
    /// </exception>
    public static IReadOnlyList<ComponentSummary> GetComponents(
        string projectRoot, string relativePath, long gameObjectFileId)
    {
        var content = LoadValidatedContent(projectRoot, relativePath);
        var objects = UnityYamlReader.Read(content, relativePath);

        var byFileId = new Dictionary<long, UnityObject>();
        foreach (var obj in objects) byFileId[obj.FileId] = obj;

        if (!byFileId.TryGetValue(gameObjectFileId, out var node))
        {
            throw new ArgumentException(
                $"GameObject fileID {gameObjectFileId} was not found in '{relativePath}'. It may "
                + "belong to a different file, or the file may have changed since it was last "
                + "inspected - call prefab_get_contents or scene_get_hierarchy again to get "
                + "current fileIds.",
                nameof(gameObjectFileId));
        }

        UnityObject gameObject;
        if (node.TypeName is "Transform" or "RectTransform")
        {
            var gameObjectRef = node.References.FirstOrDefault(r => r.PropertyPath == "m_GameObject");
            if (gameObjectRef is null || !byFileId.TryGetValue(gameObjectRef.FileId, out var owner))
            {
                throw new ArgumentException(
                    $"FileID {gameObjectFileId} in '{relativePath}' is a {node.TypeName} with no "
                    + "resolvable GameObject - the file may be corrupted or hand-edited.",
                    nameof(gameObjectFileId));
            }

            gameObject = owner;
        }
        else if (node.TypeName == "GameObject")
        {
            gameObject = node;
        }
        else
        {
            throw new ArgumentException(
                $"FileID {gameObjectFileId} in '{relativePath}' is a {node.TypeName}, not a "
                + "GameObject. component_get_all needs a GameObject's fileId, exactly as "
                + "prefab_get_contents / scene_get_hierarchy report it.",
                nameof(gameObjectFileId));
        }

        var components = new List<ComponentSummary>();
        foreach (var reference in gameObject.References)
        {
            if (reference.PropertyPath != "m_Component.component") continue;
            if (!byFileId.TryGetValue(reference.FileId, out var component)) continue;

            components.Add(new ComponentSummary
            {
                FileId = component.FileId,
                Kind = component.TypeName,
                ScriptGuid = component.TypeName == "MonoBehaviour"
                    ? component.References.FirstOrDefault(r => r.PropertyPath == "m_Script")?.Guid
                    : null,
            });
        }

        return components;
    }

    /// <summary>
    /// One object's own serialized fields, by fileId - not limited to components; a GameObject or
    /// PrefabInstance's own top-level fields read the same way. Every top-level key under the
    /// document's single outer key (e.g. "MonoBehaviour") is returned unfiltered, including
    /// Unity's own bookkeeping fields (m_Script, m_GameObject, ...) alongside a script's own
    /// exported fields - deciding which is "really" a user field would need the C# field's own
    /// type information, which this has no access to. A value is a raw string for a scalar, an
    /// <see cref="IReadOnlyDictionary{TKey,TValue}"/> for a struct or reference (Vector3, `{fileID,
    /// guid, type}`), or an <see cref="IReadOnlyList{T}"/> for a sequence - never further
    /// interpreted (numeric vs. boolean vs. enum), because Unity's own YAML does not distinguish
    /// them either without the declaring C# type.
    /// </summary>
    /// <exception cref="ArgumentException">
    /// The path escapes the project's scan roots, or no object with <paramref name="fileId"/>
    /// exists in the file.
    /// </exception>
    public static IReadOnlyDictionary<string, object?> GetComponentProperties(
        string projectRoot, string relativePath, long fileId)
    {
        var content = LoadValidatedContent(projectRoot, relativePath);

        var parser = new Parser(new StringReader(UnityYamlPreprocessor.MakeStandardYaml(content)));

        while (parser.MoveNext())
        {
            if (parser.Current is not DocumentStart) continue;
            parser.MoveNext();

            if (parser.Current is not MappingStart outer) continue;

            var anchorFileId = outer.Anchor.Value is { Length: > 0 } anchor && long.TryParse(anchor, out var parsed)
                ? parsed
                : (long?)null;

            parser.MoveNext(); // past the outer MappingStart, onto the document's one key (its type name)

            object? body = null;
            if (parser.Current is Scalar)
            {
                parser.MoveNext(); // past the type-name key, onto its value
                body = ReadNode(parser);
            }

            if (parser.Current is MappingEnd) parser.MoveNext(); // close the outer mapping

            if (anchorFileId == fileId)
            {
                return body as Dictionary<string, object?> ?? new Dictionary<string, object?>(StringComparer.Ordinal);
            }
        }

        throw new ArgumentException(
            $"Component fileID {fileId} was not found in '{relativePath}'. It may belong to a "
            + "different file, or the file may have changed since it was last inspected - call "
            + "component_get_all again to get current fileIds.",
            nameof(fileId));
    }

    /// <summary>
    /// One asset's identity: its GUID, from the sibling .meta file, and its friendly type, from
    /// its extension (<see cref="AssetType.FromPath"/>). Deliberately does not require the asset
    /// to parse as Unity YAML - unlike every other read-through entry point, this must also work
    /// for a binary asset (a texture, a model, an audio clip), which asset_get_info has no reason
    /// to refuse. A missing .meta is reported as a null <see cref="AssetInfo.Guid"/>, not an
    /// error: a file added outside the Unity Editor and not yet imported is a normal state.
    /// </summary>
    /// <exception cref="ArgumentException">The path escapes the project's scan roots.</exception>
    /// <exception cref="FileNotFoundException">The file is not on disk.</exception>
    public static AssetInfo GetAssetInfo(string projectRoot, string relativePath)
    {
        var absolutePath = ResolveAssetPath(projectRoot, relativePath);

        if (!File.Exists(absolutePath))
        {
            throw new FileNotFoundException(
                $"'{relativePath}' is not on disk. Check the path with search_by_name or asset_find "
                + "- it must be project-relative (\"Assets/...\" or \"Packages/...\"), not absolute.",
                absolutePath);
        }

        return new AssetInfo
        {
            Path = relativePath,
            Guid = MetaFileReader.TryReadGuid(absolutePath),
            Type = AssetType.FromPath(relativePath),
        };
    }

    /// <summary>
    /// The importer block from one asset's .meta file. A .meta file is plain, un-tagged YAML with
    /// SEVERAL top-level keys (fileFormatVersion, guid, optionally folderAsset, and exactly one
    /// key ending in "Importer") - structurally different from every Unity asset ReadThrough
    /// otherwise reads, which is always a single-key-per-document, %TAG-prefixed format. Reusing
    /// <see cref="UnityYamlPreprocessor.MakeStandardYaml"/> or <see cref="UnityYamlPreprocessor.LooksLikeUnityYaml"/>
    /// here would be wrong, not just unnecessary: a .meta file has no "%YAML" header for
    /// LooksLikeUnityYaml to find, and no per-document tag for MakeStandardYaml to rewrite. Still
    /// built entirely on <see cref="ReadNode"/>, the same primitive every other tree-shaped read
    /// goes through - only the outer walk (a plain multi-key mapping, not "the document's one
    /// type-name key") differs, because the .meta format itself does.
    /// </summary>
    /// <exception cref="ArgumentException">The path escapes the project's scan roots.</exception>
    /// <exception cref="FileNotFoundException">The asset has no .meta file.</exception>
    /// <exception cref="InvalidDataException">
    /// The .meta file does not parse as YAML, or has no key ending in "Importer".
    /// </exception>
    public static ImportSettingsInfo GetImportSettings(string projectRoot, string relativePath)
    {
        var absolutePath = ResolveAssetPath(projectRoot, relativePath);
        var metaPath = absolutePath + ".meta";

        if (!File.Exists(metaPath))
        {
            throw new FileNotFoundException(
                $"'{relativePath}' has no .meta file, so its import settings cannot be read. This "
                + "is expected for a file added outside the Unity Editor and not yet imported.",
                metaPath);
        }

        string content;
        try
        {
            content = File.ReadAllText(metaPath);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            throw new IOException($"'{relativePath}'.meta could not be read: {ex.Message}", ex);
        }

        var top = ReadPlainYamlMapping(content, relativePath);

        foreach (var (key, value) in top)
        {
            if (key.EndsWith("Importer", StringComparison.Ordinal) && value is Dictionary<string, object?> settings)
            {
                return new ImportSettingsInfo { Path = relativePath, ImporterType = key, Settings = settings };
            }
        }

        throw new InvalidDataException(
            $"'{relativePath}'.meta has no recognisable importer block - it may be in a format "
            + "Hades does not recognise.");
    }

    /// <summary>
    /// One material's shader and properties. A material asset is NOT always exactly one YAML
    /// document - confirmed against the real Hades-Unity-Client corpus, where a URP material
    /// (M_Enemy.mat) carries an editor-only "AssetVersion" MonoBehaviour document BEFORE its own
    /// Material document. Reading "the first document" (as an earlier version of this method did,
    /// and as <see cref="GetSettingsAsset"/> correctly does for its own callers, which really are
    /// always single-document) silently returned an empty, wrong result on that exact file rather
    /// than failing loudly - caught by the real-project smoke test, not by review. This instead
    /// finds the document Unity itself declares as "Material" via <see cref="UnityYamlReader"/>
    /// (<see cref="UnityObject.DeclaredTypeName"/>, the same field <see cref="GetAnimatorController"/>
    /// keys off for the same reason), then reads THAT document's raw field tree via
    /// <see cref="ReadAllDocumentTrees"/> - never <see cref="UnityYamlReader"/>'s flat reference
    /// extraction, because m_Floats and m_Colors are plain scalars/structs it never captures at all
    /// (it only tracks anchor, name, references and modifications). The shader and every SET
    /// texture's guid are resolved to a path in one on-disk pass via
    /// <see cref="ResolveGuidsToPaths"/> - never the graph, since neither shaders nor textures are
    /// indexed there (see that method's own doc comment for why). A shader guid that does not
    /// resolve does not fail the call: every other property is still returned, with the shader
    /// reported as unresolved - a material referencing a built-in or package shader is the common
    /// case, not a broken one.
    /// </summary>
    /// <exception cref="ArgumentException">The path escapes the project's scan roots.</exception>
    /// <exception cref="FileNotFoundException">The file is not on disk.</exception>
    /// <exception cref="InvalidDataException">
    /// The file is not text Unity YAML, does not parse cleanly all the way through, or has no
    /// document Unity itself declares as "Material".
    /// </exception>
    public static MaterialProperties GetMaterialProperties(string projectRoot, string relativePath)
    {
        var content = LoadValidatedContent(projectRoot, relativePath);

        var materialObject = UnityYamlReader.Read(content, relativePath)
            .FirstOrDefault(o => o.DeclaredTypeName == "Material")
            ?? throw new InvalidDataException(
                $"'{relativePath}' has no document Unity declares as \"Material\" - it may not "
                + "actually be a material asset.");

        var document = ReadAllDocumentTrees(content).GetValueOrDefault(materialObject.FileId)
            ?? new Dictionary<string, object?>(StringComparer.Ordinal);

        var shaderGuid = ReferenceGuid(document.GetValueOrDefault("m_Shader"));

        var saved = document.GetValueOrDefault("m_SavedProperties") as Dictionary<string, object?>;
        var floats = FlattenNamedList(saved?.GetValueOrDefault("m_Floats"))
            .ToDictionary(kv => kv.Key, kv => kv.Value as string ?? "", StringComparer.Ordinal);
        var colors = FlattenNamedList(saved?.GetValueOrDefault("m_Colors"))
            .ToDictionary(kv => kv.Key,
                kv => (IReadOnlyDictionary<string, object?>)(kv.Value as Dictionary<string, object?>
                    ?? new Dictionary<string, object?>(StringComparer.Ordinal)),
                StringComparer.Ordinal);

        // Only slots with something assigned - {fileID: 0} is Unity's own "nothing here" and
        // reporting all dozen-plus empty texture slots on every material would bury the one set.
        var textureSlots = FlattenNamedList(saved?.GetValueOrDefault("m_TexEnvs"))
            .Select(kv => (Property: kv.Key,
                Guid: ReferenceGuid((kv.Value as Dictionary<string, object?>)?.GetValueOrDefault("m_Texture"))))
            .Where(slot => slot.Guid is not null)
            .ToList();

        var guidsToResolve = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        if (shaderGuid is not null) guidsToResolve.Add(shaderGuid);
        foreach (var slot in textureSlots) guidsToResolve.Add(slot.Guid!);

        var resolved = ResolveGuidsToPaths(projectRoot, guidsToResolve);

        return new MaterialProperties
        {
            Path = relativePath,
            Shader = ToReference(shaderGuid, resolved),
            Floats = floats,
            Colors = colors,
            Textures = textureSlots.Select(slot => new MaterialTexture
            {
                Property = slot.Property,
                Guid = slot.Guid,
                Path = resolved.GetValueOrDefault(slot.Guid!),
                Resolved = resolved.ContainsKey(slot.Guid!),
            }).ToList(),
        };
    }

    /// <summary>
    /// Every asset, anywhere under a scan root, whose .meta GUID is in <paramref name="guids"/> -
    /// the reverse of the usual path-to-GUID direction, and deliberately NOT the graph: a shader
    /// or texture is routinely a built-in or package asset with no file under any scan root at
    /// all, but when it IS project-local, neither .shader nor image/audio/model extensions are in
    /// AssetIndexer's indexed set, so <see cref="Graph.GraphDatabase.PathForGuid"/> would never
    /// resolve even a project-local texture - which would make "resolved from GUID to asset path"
    /// silently never work for the exact case (a project's own textures) it most needs to. A
    /// one-shot on-disk search instead: reuses <see cref="ProjectWalker"/>'s own scan-root
    /// enumeration and <see cref="MetaFileReader.TryReadGuid"/> exactly as the indexer does,
    /// stopping the moment every requested guid is found rather than always walking the whole
    /// project. A guid nothing owns is simply absent from the result, not present with a null
    /// path - callers check with the same TryGetValue/ContainsKey idiom either way.
    /// </summary>
    public static IReadOnlyDictionary<string, string> ResolveGuidsToPaths(string projectRoot, IReadOnlySet<string> guids)
    {
        var found = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        if (guids.Count == 0) return found;

        var remaining = new HashSet<string>(guids, StringComparer.OrdinalIgnoreCase);
        var warnings = new List<string>();

        foreach (var root in ProjectWalker.ResolveScanRoots(projectRoot, warnings))
        {
            if (remaining.Count == 0) break;

            foreach (var metaFile in ProjectWalker.EnumerateSourceFiles(root.AbsolutePath, "*.meta"))
            {
                if (remaining.Count == 0) break;

                var assetPath = metaFile[..^".meta".Length];
                if (MetaFileReader.TryReadGuid(assetPath) is not { } guid || !remaining.Remove(guid)) continue;

                found[guid] = ProjectWalker.ToRecordedPath(root, assetPath);
            }
        }

        return found;
    }

    /// <summary>
    /// The external GUID a raw {fileID, guid} reference node names, or null when it is Unity's own
    /// null reference ({fileID: 0}, no guid) or a LOCAL (same-file, no guid) reference - meaningless
    /// here, since a material's shader and texture references are always to another asset.
    /// </summary>
    static string? ReferenceGuid(object? raw)
    {
        if (raw is not Dictionary<string, object?> reference) return null;
        return reference.GetValueOrDefault("guid") as string is { Length: > 0 } guid ? guid : null;
    }

    static AssetReference ToReference(string? guid, IReadOnlyDictionary<string, string> resolved) => new()
    {
        Guid = guid,
        Path = guid is not null ? resolved.GetValueOrDefault(guid) : null,
        Resolved = guid is not null && resolved.ContainsKey(guid),
    };

    /// <summary>
    /// Flattens a sequence of single-key mappings into (name, value) pairs - the shape Unity
    /// writes m_Floats/m_Colors/m_TexEnvs in: <c>- _Metallic: 0.5</c> is a one-entry block mapping
    /// per sequence item, not a "name:"/"value:" pair under a shared key. Tolerates a missing or
    /// differently-shaped field by degrading to empty rather than throwing - a material's exact
    /// property set is shader-dependent and this must not assume any one shader's shape.
    /// </summary>
    static IEnumerable<KeyValuePair<string, object?>> FlattenNamedList(object? raw)
    {
        if (raw is not List<object?> items) yield break;

        foreach (var item in items)
        {
            if (item is not Dictionary<string, object?> { Count: 1 } entry) continue;
            var pair = entry.First();
            yield return pair;
        }
    }

    /// <summary>
    /// States and transitions across every layer's state machine in one .controller file.
    ///
    /// Built on TWO complementary reads of the same file, because neither alone carries every
    /// fact needed. <see cref="UnityYamlReader"/> supplies document identity (fileId,
    /// <see cref="UnityObject.DeclaredTypeName"/> - not <see cref="UnityObject.TypeName"/>, since
    /// AnimatorState/AnimatorStateTransition/AnimatorStateMachine's class ids only recently
    /// gained UnityClassIds entries; DeclaredTypeName has always been reliable, direct from the
    /// document) plus the handful of references it captures correctly (m_DstState, m_State,
    /// m_DefaultState - each a key immediately followed by a flow mapping). It canNOT supply a
    /// state's own m_Transitions or a state machine's m_AnyStateTransitions: both are bare
    /// <c>{fileID: ...}</c> flow mappings written directly under a sequence with no per-item key,
    /// and UnityYamlReader's reference detection only fires for a flow mapping that follows a key
    /// - the exact same shape, for the exact same reason, as the m_Children gotcha
    /// <see cref="BuildHierarchy"/> already documents. <see cref="ReadAllDocumentTrees"/> (the raw
    /// ReadNode tree, keyed by fileId, for every document at once) fills that gap - it is also
    /// what supplies m_Conditions, which is not a reference at all.
    /// </summary>
    /// <exception cref="ArgumentException">The path escapes the project's scan roots.</exception>
    /// <exception cref="FileNotFoundException">The file is not on disk.</exception>
    /// <exception cref="InvalidDataException">
    /// The file is not text Unity YAML, or does not parse cleanly all the way through.
    /// </exception>
    public static AnimatorControllerInfo GetAnimatorController(string projectRoot, string relativePath)
    {
        var content = LoadValidatedContent(projectRoot, relativePath);
        var objects = UnityYamlReader.Read(content, relativePath);
        var trees = ReadAllDocumentTrees(content);

        var byFileId = objects.ToDictionary(o => o.FileId);
        var states = objects.Where(o => o.DeclaredTypeName == "AnimatorState").ToList();
        var transitions = objects.Where(o => o.DeclaredTypeName == "AnimatorStateTransition").ToList();
        var stateMachines = objects.Where(o => o.DeclaredTypeName == "AnimatorStateMachine").ToList();

        var defaultStateIds = stateMachines
            .Select(machine => machine.References.FirstOrDefault(r => r.PropertyPath == "m_DefaultState"))
            .Where(reference => reference is not null)
            .Select(reference => reference!.FileId)
            .ToHashSet();

        // Which state (by name) owns each transition fileId - the fact m_Transitions/
        // m_AnyStateTransitions carry that no reference edge does (see this method's own doc
        // comment). "Any State" is Unity's own name for the pseudo-state every state machine
        // implicitly has; a transition claimed by neither is left with a null source rather than
        // a guess - not expected in a well-formed controller, but a hand-edited one is not this
        // method's problem to reject outright when everything else about it still parses.
        var sourceOfTransition = new Dictionary<long, string>();
        foreach (var state in states)
        {
            if (!trees.TryGetValue(state.FileId, out var tree)) continue;
            foreach (var transitionId in ReferencedFileIds(tree.GetValueOrDefault("m_Transitions")))
                sourceOfTransition[transitionId] = state.Name ?? "";
        }
        foreach (var machine in stateMachines)
        {
            if (!trees.TryGetValue(machine.FileId, out var tree)) continue;
            foreach (var transitionId in ReferencedFileIds(tree.GetValueOrDefault("m_AnyStateTransitions")))
                sourceOfTransition[transitionId] = "Any State";
        }

        string? NameOf(long fileId) => byFileId.TryGetValue(fileId, out var obj) ? obj.Name : null;

        return new AnimatorControllerInfo
        {
            Path = relativePath,
            States = states.Select(s => new AnimatorStateInfo
            {
                FileId = s.FileId,
                Name = s.Name ?? "",
                IsDefaultState = defaultStateIds.Contains(s.FileId),
            }).ToList(),
            Transitions = transitions.Select(t =>
            {
                // {fileID: 0} (an exit transition, m_IsExit: 1) is Unity's null reference and is
                // never added to References at all - see UnityYamlReader.ToReference - so a
                // missing m_DstState reference here IS the exit-transition signal, not a parse gap.
                var destination = t.References.FirstOrDefault(r => r.PropertyPath == "m_DstState");

                return new AnimatorTransitionInfo
                {
                    FileId = t.FileId,
                    SourceState = sourceOfTransition.GetValueOrDefault(t.FileId),
                    DestinationState = destination is not null ? NameOf(destination.FileId) : null,
                    Conditions = trees.TryGetValue(t.FileId, out var tree)
                        ? ReadConditions(tree.GetValueOrDefault("m_Conditions"))
                        : [],
                };
            }).ToList(),
        };
    }

    /// <summary>Every fileId in a sequence of bare <c>{fileID: ...}</c> flow mappings - the shape
    /// <see cref="UnityYamlReader"/> cannot capture as a reference (see
    /// <see cref="GetAnimatorController"/>'s doc comment), read instead from the raw
    /// <see cref="ReadNode"/> tree.</summary>
    static IEnumerable<long> ReferencedFileIds(object? raw)
    {
        if (raw is not List<object?> items) yield break;

        foreach (var item in items)
        {
            if (item is Dictionary<string, object?> reference
                && reference.GetValueOrDefault("fileID") is string rawFileId
                && long.TryParse(rawFileId, out var fileId))
            {
                yield return fileId;
            }
        }
    }

    /// <summary>A transition's m_Conditions, raw - Unity's own numeric AnimatorConditionMode left
    /// uninterpreted, like every other scalar ReadThrough returns.</summary>
    static IReadOnlyList<AnimatorConditionInfo> ReadConditions(object? raw)
    {
        if (raw is not List<object?> items) return [];

        var conditions = new List<AnimatorConditionInfo>();
        foreach (var item in items)
        {
            if (item is not Dictionary<string, object?> condition) continue;

            conditions.Add(new AnimatorConditionInfo
            {
                Parameter = condition.GetValueOrDefault("m_ConditionEvent") as string ?? "",
                ConditionMode = condition.GetValueOrDefault("m_ConditionMode") as string ?? "",
                Threshold = condition.GetValueOrDefault("m_EventTreshold") as string ?? "",
            });
        }

        return conditions;
    }

    /// <summary>
    /// Every document in <paramref name="content"/> as a raw <see cref="ReadNode"/> tree, keyed by
    /// fileId - the same per-document walk <see cref="GetComponentProperties"/> does when it finds
    /// its one matching anchor, generalised to collect all of them in a single pass instead of
    /// stopping at the first match. <see cref="GetAnimatorController"/> needs arbitrarily many
    /// documents' raw fields (every state's m_Transitions, every state machine's
    /// m_AnyStateTransitions, every transition's m_Conditions), and re-parsing the whole file once
    /// per document would be wasteful for a controller with many states - the exact same reasoning
    /// <see cref="Reading.ReferenceReading.FindUnsetReferences"/> relies on to scan every object in
    /// a file once rather than once per object. Internal rather than private for that second
    /// caller, in a different file by design - see ReferenceReading's own class doc comment for why
    /// it is not folded into this already-large one.
    /// </summary>
    internal static Dictionary<long, Dictionary<string, object?>> ReadAllDocumentTrees(string content)
    {
        var trees = new Dictionary<long, Dictionary<string, object?>>();
        var parser = new Parser(new StringReader(UnityYamlPreprocessor.MakeStandardYaml(content)));

        while (parser.MoveNext())
        {
            if (parser.Current is not DocumentStart) continue;
            parser.MoveNext();

            if (parser.Current is not MappingStart outer) continue;

            var anchorFileId = outer.Anchor.Value is { Length: > 0 } anchor && long.TryParse(anchor, out var parsed)
                ? parsed
                : (long?)null;

            parser.MoveNext(); // past the outer MappingStart, onto the document's one key (its type name)

            object? body = null;
            if (parser.Current is Scalar)
            {
                parser.MoveNext(); // past the type-name key, onto its value
                body = ReadNode(parser);
            }

            if (parser.Current is MappingEnd) parser.MoveNext(); // close the outer mapping

            if (anchorFileId is { } fileId && body is Dictionary<string, object?> dict) trees[fileId] = dict;
        }

        return trees;
    }

    /// <summary>
    /// Walks a plain YAML mapping's top-level keys generically, via <see cref="ReadNode"/> for
    /// both key and value - unlike <see cref="ReadFirstDocument"/>, this makes no assumption that
    /// the document has exactly one top-level key, because a .meta file (the one caller today)
    /// never does.
    /// </summary>
    static Dictionary<string, object?> ReadPlainYamlMapping(string content, string displayName)
    {
        try
        {
            var parser = new Parser(new StringReader(content));

            while (parser.MoveNext())
            {
                if (parser.Current is not DocumentStart) continue;
                parser.MoveNext();

                if (parser.Current is not MappingStart) break;
                parser.MoveNext();

                var map = new Dictionary<string, object?>(StringComparer.Ordinal);
                while (parser.Current is not MappingEnd)
                {
                    var key = ReadNode(parser) as string
                        ?? throw new InvalidDataException(
                            $"'{displayName}'.meta has an unexpected structure - a non-scalar top-level key.");
                    map[key] = ReadNode(parser);
                }

                return map;
            }
        }
        catch (YamlException ex)
        {
            throw new InvalidDataException(
                $"'{displayName}'.meta could not be parsed as YAML - it may be malformed or "
                + "truncated (for example, caught mid-write).", ex);
        }

        throw new InvalidDataException($"'{displayName}'.meta contains no readable YAML document.");
    }

    /// <summary>
    /// Reads one YAML node - scalar, sequence, or mapping - into a plain CLR value, consuming
    /// exactly that node's events (through its matching End event) and nothing more, so the
    /// caller's own traversal stays aligned afterward. Deliberately the document-model shape
    /// (<see cref="Dictionary{TKey,TValue}"/> / <see cref="List{T}"/> / string) rather than
    /// UnityYamlReader's flat reference/property-path extraction: that shape exists to answer
    /// "what does this reference", not "what is this component's Nth field", and component
    /// properties need the latter, arbitrarily nested. Works on the same event-level
    /// <see cref="IParser"/> UnityYamlReader itself uses rather than YamlDotNet's document model,
    /// for the same reason UnityYamlReader does: an event walk never constructs a mapping, so
    /// duplicate keys (Animator controllers) cannot make it throw the way YamlStream does. A
    /// duplicate key here resolves last-write-wins, which is what a hand-rolled mapping walk does
    /// naturally without extra code to special-case it.
    /// </summary>
    static object? ReadNode(IParser parser)
    {
        switch (parser.Current)
        {
            case Scalar scalar:
                parser.MoveNext();
                return scalar.Value;

            case SequenceStart:
                parser.MoveNext();
                var list = new List<object?>();
                while (parser.Current is not SequenceEnd) list.Add(ReadNode(parser));
                parser.MoveNext(); // consume SequenceEnd
                return list;

            case MappingStart:
                parser.MoveNext();
                var map = new Dictionary<string, object?>(StringComparer.Ordinal);
                while (parser.Current is not MappingEnd)
                {
                    var key = ReadNode(parser) as string
                        ?? throw new InvalidDataException("Expected a scalar mapping key while reading component properties.");
                    map[key] = ReadNode(parser);
                }
                parser.MoveNext(); // consume MappingEnd
                return map;

            default:
                throw new InvalidDataException(
                    $"Unexpected YAML event '{parser.Current?.GetType().Name}' while reading component properties.");
        }
    }

    /// <summary>
    /// Resolves and validates a caller-supplied path down to its text content: containment
    /// (<see cref="ResolveAssetPath"/>), on-disk existence, readability, and that it parses as
    /// well-formed Unity YAML all the way through. Shared by every read-through entry point
    /// (<see cref="GetHierarchy"/>, <see cref="GetComponents"/>, <see cref="GetComponentProperties"/>,
    /// and - internal, from <see cref="Reading.ReferenceReading.FindUnsetReferences"/> -
    /// <see cref="ReadAllDocumentTrees"/>'s one external caller) so this guard is written, and
    /// reasoned about, exactly once.
    /// </summary>
    /// <exception cref="ArgumentException">The path escapes the project's scan roots.</exception>
    /// <exception cref="FileNotFoundException">The file is no longer on disk.</exception>
    /// <exception cref="InvalidDataException">
    /// The file is not text Unity YAML, or does not parse cleanly all the way through.
    /// </exception>
    internal static string LoadValidatedContent(string projectRoot, string relativePath)
    {
        var absolutePath = ResolveAssetPath(projectRoot, relativePath);

        if (!File.Exists(absolutePath))
        {
            throw new FileNotFoundException(
                $"'{relativePath}' is no longer on disk. It may have been deleted or moved since "
                + "it was indexed; hades_rebuild_graph will bring the index back in sync.",
                absolutePath);
        }

        return LoadValidatedContentAt(absolutePath, relativePath);
    }

    /// <summary>
    /// The read-and-validate tail shared by every read-through entry point once it has an
    /// absolute path in hand and has confirmed the file exists: read it, confirm it looks like
    /// Unity YAML, confirm it parses cleanly all the way through. Split out from
    /// <see cref="LoadValidatedContent"/> so <see cref="GetSettingsAsset"/> can share it too -
    /// its own not-found case needs a different message (a fixed ProjectSettings file was never
    /// "indexed", so that framing would be wrong), but everything after "the file exists" is
    /// identical.
    /// </summary>
    static string LoadValidatedContentAt(string absolutePath, string displayName)
    {
        string content;
        try
        {
            content = File.ReadAllText(absolutePath);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            throw new IOException($"'{displayName}' could not be read: {ex.Message}", ex);
        }

        if (!UnityYamlPreprocessor.LooksLikeUnityYaml(content))
        {
            throw new InvalidDataException(
                $"'{displayName}' is not a Unity text asset Hades can read through - it is "
                + "binary, empty, or in an unrecognised format.");
        }

        // UnityYamlReader.Read swallows a YamlException and returns whatever was read before the
        // fault - the right call for a best-effort indexing sweep, but wrong here: read-through
        // must never hand back a partial result as if it were complete. Re-verified
        // independently, using the same preprocessing and the same parser, before trusting
        // anything downstream produces.
        if (!ParsesCleanly(content))
        {
            throw new InvalidDataException(
                $"'{displayName}' could not be parsed as YAML - the file may be malformed or "
                + "truncated (for example, caught mid-write).");
        }

        return content;
    }

    /// <summary>
    /// Reads one of Unity's fixed ProjectSettings/*.asset files - ProjectSettings.asset,
    /// TagManager.asset, EditorBuildSettings.asset - into its full field tree: the same
    /// single-document <see cref="ReadNode"/> walk <see cref="GetComponentProperties"/> uses.
    ///
    /// Unlike every other read-through entry point, <paramref name="relativePath"/> is never
    /// caller-supplied - project_get_settings, tag_list, layer_list and scene_list_build take no
    /// path argument at all, only ever one of these three fixed, Unity-owned filenames a tool
    /// builds itself. <see cref="ResolveAssetPath"/>'s containment guard therefore does not apply:
    /// it exists to police a path a CALLER sent, and ProjectSettings/ is not even one of the
    /// project's scan roots (Assets/, Packages/, a local package) that guard resolves against.
    /// Each of these files is exactly one YAML document, so unlike
    /// <see cref="GetComponentProperties"/> there is no fileId to select by either - this always
    /// reads the first (and only) document.
    /// </summary>
    /// <param name="relativePath">Project-relative, e.g. "ProjectSettings/TagManager.asset" -
    /// fixed by the caller (a tool), never taken from an MCP argument.</param>
    /// <exception cref="FileNotFoundException">The file does not exist.</exception>
    /// <exception cref="InvalidDataException">
    /// The file is not text Unity YAML, or does not parse cleanly all the way through.
    /// </exception>
    public static IReadOnlyDictionary<string, object?> GetSettingsAsset(string projectRoot, string relativePath)
    {
        var absolutePath = Path.Combine(projectRoot, relativePath.Replace('/', Path.DirectorySeparatorChar));

        if (!File.Exists(absolutePath))
        {
            throw new FileNotFoundException(
                $"'{relativePath}' was not found under the project root. Unity writes this file "
                + "automatically; a project that has never been opened in the Unity Editor may not "
                + "have it yet.",
                absolutePath);
        }

        var content = LoadValidatedContentAt(absolutePath, relativePath);
        return ReadFirstDocument(content, relativePath);
    }

    /// <summary>
    /// Unity's own, version-stable script guid for UniversalRenderPipelineAsset.cs (package
    /// com.unity.render-pipelines.universal). Confirmed EMPIRICALLY, not guessed: the real
    /// Hades-Unity-Client project (URP 17.3.0) has GraphicsSettings.asset's m_CustomRenderPipeline
    /// resolving to Assets/Settings/PC_RPAsset.asset, whose own m_Script names exactly this guid.
    /// </summary>
    const string UniversalRenderPipelineAssetScriptGuid = "bf2edee5c58d82540a51f03df9d42094";

    /// <summary>
    /// Unity's own, version-stable script guid for HDRenderPipelineAsset.cs (package
    /// com.unity.render-pipelines.high-definition). Hades has no HDRP project to confirm this
    /// against empirically the way <see cref="UniversalRenderPipelineAssetScriptGuid"/> is
    /// confirmed - taken instead directly from Unity's own published source
    /// (github.com/Unity-Technologies/Graphics, Runtime/RenderPipeline/HDRenderPipelineAsset.cs.meta),
    /// not from memory or a guess.
    /// </summary>
    const string HighDefinitionRenderPipelineAssetScriptGuid = "0cf1dab834d4ec34195b920ea7bbf9ec";

    /// <summary>
    /// Which render pipeline the project is configured to use, read from
    /// ProjectSettings/GraphicsSettings.asset's m_CustomRenderPipeline. A null reference there
    /// (Unity's own convention: {fileID: 0}, no guid) means the Built-in Render Pipeline - no
    /// custom SRP configured at all. Otherwise, the referenced asset is resolved by guid (via
    /// <see cref="ResolveGuidsToPaths"/> - an on-disk search, not the graph, for the same reason
    /// <see cref="GetMaterialProperties"/> does not use the graph for a shader guid: neither a
    /// render pipeline asset's OWN identity nor its containing package is something the graph
    /// indexes) and its own m_Script guid is compared against the two well-known constants above.
    ///
    /// Deliberately an exact match against a known-stable identifier, not a partial or fuzzy one -
    /// "the referenced asset's script IS this exact URP/HDRP class" is verifiable ground truth,
    /// where "the guid looks like it is probably URP" would not be. Reported as "unknown" - never
    /// guessed - whenever that bar is not cleared: a third-party or hand-rolled SRP, or a resolved
    /// asset Hades cannot read for some other reason.
    /// </summary>
    /// <exception cref="FileNotFoundException">GraphicsSettings.asset does not exist.</exception>
    /// <exception cref="InvalidDataException">GraphicsSettings.asset does not parse as YAML.</exception>
    public static RenderPipelineInfo AnalyzeRenderPipeline(string projectRoot)
    {
        var document = GetSettingsAsset(projectRoot, "ProjectSettings/GraphicsSettings.asset");
        var pipelineGuid = ReferenceGuid(document.GetValueOrDefault("m_CustomRenderPipeline"));

        if (pipelineGuid is null)
        {
            return new RenderPipelineInfo { Pipeline = "Built-in", PipelineAssetPath = null };
        }

        var resolved = ResolveGuidsToPaths(projectRoot, new HashSet<string> { pipelineGuid });
        if (!resolved.TryGetValue(pipelineGuid, out var assetPath))
        {
            // A custom pipeline IS configured, but the asset that would identify it is not under
            // any scan root Hades walks (e.g. a package-provided default) - unidentifiable, same
            // as an unrecognised script guid below, just for a different reason.
            return new RenderPipelineInfo { Pipeline = "unknown", PipelineAssetPath = null };
        }

        string? scriptGuid = null;
        try
        {
            var assetContent = LoadValidatedContent(projectRoot, assetPath);

            // Not "the first document": GetMaterialProperties' own real-corpus lesson applies
            // here too - a render pipeline asset is not guaranteed to be exactly one document
            // either, so every document's m_Script is checked rather than assuming position.
            scriptGuid = ReadAllDocumentTrees(assetContent).Values
                .Select(tree => ReferenceGuid(tree.GetValueOrDefault("m_Script")))
                .FirstOrDefault(guid => guid is not null);
        }
        catch (Exception ex) when (ex is FileNotFoundException or InvalidDataException or IOException)
        {
            // The asset resolved but could not be read - degrade to unknown rather than fail the
            // whole call over one unreadable file when the question asked ("which pipeline?") can
            // still be answered honestly as "cannot tell".
        }

        var pipeline = scriptGuid switch
        {
            UniversalRenderPipelineAssetScriptGuid => "URP",
            HighDefinitionRenderPipelineAssetScriptGuid => "HDRP",
            _ => "unknown",
        };

        // The path is reported even when unrecognised - "found, but not identifiable as URP or
        // HDRP" is more useful than hiding evidence just because classification came up short.
        return new RenderPipelineInfo { Pipeline = pipeline, PipelineAssetPath = assetPath };
    }

    /// <summary>
    /// Parses <paramref name="content"/>'s first YAML document into its full field tree via
    /// <see cref="ReadNode"/> - the same shape <see cref="GetComponentProperties"/> returns for
    /// one component, generalised to "the document" rather than "the document whose anchor
    /// matches a given fileId". Safe to parse without a YamlException guard: the caller already
    /// confirmed <paramref name="content"/> parses cleanly, via the exact same preprocessing and
    /// parser, in <see cref="LoadValidatedContentAt"/>.
    /// </summary>
    static IReadOnlyDictionary<string, object?> ReadFirstDocument(string content, string displayName)
    {
        var parser = new Parser(new StringReader(UnityYamlPreprocessor.MakeStandardYaml(content)));

        while (parser.MoveNext())
        {
            if (parser.Current is not DocumentStart) continue;
            parser.MoveNext();

            if (parser.Current is not MappingStart) break;
            parser.MoveNext(); // past the outer MappingStart, onto the document's one key (its type name)

            if (parser.Current is not Scalar) break;
            parser.MoveNext(); // past the type-name key, onto its value

            return ReadNode(parser) as Dictionary<string, object?>
                ?? new Dictionary<string, object?>(StringComparer.Ordinal);
        }

        throw new InvalidDataException($"'{displayName}' contains no readable YAML document.");
    }

    /// <summary>True when the file parses as well-formed YAML all the way through.</summary>
    static bool ParsesCleanly(string content)
    {
        try
        {
            var parser = new Parser(new StringReader(UnityYamlPreprocessor.MakeStandardYaml(content)));
            while (parser.MoveNext()) { }
            return true;
        }
        catch (YamlException)
        {
            return false;
        }
    }

    /// <summary>
    /// Walks every path segment from <paramref name="rootAbsolute"/> down to
    /// <paramref name="candidateAbsolute"/>, resolving any symlink found along the way and
    /// re-checking containment against its real target. <see cref="FileInfo.ResolveLinkTarget"/>
    /// resolves a link regardless of whether the segment is itself a file or a directory - a
    /// symlinked directory ("Assets/Evil" pointing elsewhere) is exactly the case a plain
    /// <see cref="File.Exists"/> plus string-prefix check would miss, since the final path
    /// component being read is a perfectly ordinary file once you are through the symlinked
    /// ancestor.
    /// </summary>
    static bool EscapesRootViaSymlink(string rootAbsolute, string candidateAbsolute)
    {
        var relative = Path.GetRelativePath(rootAbsolute, candidateAbsolute);
        var current = rootAbsolute;

        foreach (var segment in relative.Split(Path.DirectorySeparatorChar))
        {
            if (segment is "" or ".") continue;
            current = Path.Combine(current, segment);

            string? target;
            try
            {
                // Throws FileNotFoundException/DirectoryNotFoundException (both IOException) when
                // this segment does not exist at all - not a symlink, not an escape, just missing.
                // GetHierarchy's own File.Exists check reports that clearly; this must not let a
                // path resolution artefact preempt it with a confusing default BCL message.
                target = new FileInfo(current).ResolveLinkTarget(returnFinalTarget: true)?.FullName;
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
            {
                continue;
            }

            if (target is null) continue;   // this segment is not itself a symlink

            if (target.Length <= rootAbsolute.Length
                || !target.StartsWith(rootAbsolute + Path.DirectorySeparatorChar, StringComparison.Ordinal))
            {
                return true;
            }
        }

        return false;
    }

    /// <summary>
    /// Builds the GameObject tree from a file's parsed objects. Reconstructs parenting from each
    /// Transform's <c>m_Father</c> file ID - order is not guaranteed in the file (a child's
    /// Transform can appear before its parent's), so every node is collected into a flat map
    /// first and linked into a tree only afterward, never assuming document order is hierarchy
    /// order.
    ///
    /// A nested or variant prefab instance gets a placeholder node rather than being resolved
    /// into the base prefab, which would be cross-file work read-through does not do. Two shapes
    /// of placeholder occur, both real in the Hades-Unity-Client corpus:
    ///   - a <c>stripped</c> Transform, linked to its owning PrefabInstance by the Transform's
    ///     own <c>m_PrefabInstance</c> reference (a nested instance under a local GameObject -
    ///     e.g. Assets/Prefabs/NestTest/Wrapper.prefab);
    ///   - a PrefabInstance with no local stripped Transform at all, for a pure prefab variant -
    ///     the entire file is that one document (e.g. Assets/Prefabs/SmokeTestCube_Variant.prefab,
    ///     and 3 of the 9 Demo/Prefabs entries). Its own <c>m_TransformParent</c> supplies the
    ///     parent link (null means it is the file's own root).
    /// <c>m_Children</c> is NOT a usable signal here: Unity writes each entry as a bare flow
    /// mapping directly under the sequence, with no key in front of it, and UnityYamlReader's
    /// reference detection only fires for a flow mapping that follows a key - so, unlike
    /// <c>m_Father</c>, <c>m_Children</c> entries are never extracted as references at all
    /// (confirmed empirically before writing this). <c>m_PrefabInstance</c> is what fills the gap
    /// for the one case that would otherwise leave a node unreachable: a stripped Transform never
    /// carries its own <c>m_Father</c>.
    /// </summary>
    static AssetHierarchy BuildHierarchy(string relativePath, IReadOnlyList<UnityObject> objects)
    {
        var byFileId = new Dictionary<long, UnityObject>();
        foreach (var obj in objects) byFileId[obj.FileId] = obj;

        var instances = new Dictionary<long, PrefabInstanceInfo>();
        foreach (var obj in objects)
        {
            if (PrefabInstanceReader.TryRead(obj) is { } info) instances[info.FileId] = info;
        }

        var nodes = new Dictionary<long, HierarchyNode>();
        var orderedIds = new List<long>();
        var parentOf = new Dictionary<long, long>();

        // A PrefabInstance already represented by a local stripped placeholder must not ALSO get
        // a synthetic node below - the placeholder IS its node.
        var claimedInstances = new HashSet<long>();

        foreach (var obj in objects)
        {
            if (obj.TypeName is not ("Transform" or "RectTransform")) continue;

            if (obj.IsStripped)
            {
                var instanceRef = obj.References.FirstOrDefault(r => r.PropertyPath == "m_PrefabInstance");
                var owner = instanceRef is not null && instances.TryGetValue(instanceRef.FileId, out var found)
                    ? found : null;
                if (owner is not null) claimedInstances.Add(owner.FileId);

                AddNode(obj.FileId, "PrefabInstance", name: null,
                    sourcePrefabGuid: owner?.SourcePrefab.Guid ?? obj.CorrespondingSourceObject?.Guid,
                    components: []);

                if (owner?.TransformParent?.FileId is { } ownerParentId) parentOf[obj.FileId] = ownerParentId;
                continue;
            }

            var gameObjectRef = obj.References.FirstOrDefault(r => r.PropertyPath == "m_GameObject");
            var gameObject = gameObjectRef is not null && byFileId.TryGetValue(gameObjectRef.FileId, out var go)
                ? go : null;

            var components = (gameObject?.References ?? [])
                .Where(r => r.PropertyPath == "m_Component.component")
                .Select(r => byFileId.TryGetValue(r.FileId, out var component) ? component.TypeName : null)
                .Where(kind => kind is not (null or "Transform" or "RectTransform"))
                .Select(kind => kind!)
                .ToList();

            AddNode(obj.FileId, "GameObject", gameObject?.Name, sourcePrefabGuid: null, components);

            var fatherRef = obj.References.FirstOrDefault(r => r.PropertyPath == "m_Father");
            if (fatherRef is not null) parentOf[obj.FileId] = fatherRef.FileId;
        }

        // Anything left over is a PrefabInstance nothing local claimed - a pure variant root, or
        // (defensively) a nested instance Unity happened not to give a stripped placeholder.
        foreach (var (fileId, instance) in instances)
        {
            if (claimedInstances.Contains(fileId)) continue;

            AddNode(fileId, "PrefabInstance", name: null, sourcePrefabGuid: instance.SourcePrefab.Guid, components: []);
            if (instance.TransformParent?.FileId is { } parentId) parentOf[fileId] = parentId;
        }

        return new AssetHierarchy { Path = relativePath, Roots = Link(orderedIds, nodes, parentOf) };

        void AddNode(long fileId, string kind, string? name, string? sourcePrefabGuid, IReadOnlyList<string> components)
        {
            nodes[fileId] = new HierarchyNode
            {
                FileId = fileId,
                Kind = kind,
                Name = name,
                SourcePrefabGuid = sourcePrefabGuid,
                Components = components,
                Children = [],
            };
            orderedIds.Add(fileId);
        }
    }

    /// <summary>
    /// Assembles the flat node/parent map into a nested tree, in the order nodes were discovered
    /// (document order), starting from every node with no known parent - or whose recorded parent
    /// is not itself a node in this file - and walking down. A visited set guards against a
    /// cycle: Unity should never produce one, but this must degrade gracefully rather than
    /// recurse forever if a hand-edited file has one. Anything a cycle leaves unreachable from
    /// every root is still surfaced afterward as an extra root, rather than silently dropped.
    /// </summary>
    static IReadOnlyList<HierarchyNode> Link(
        List<long> orderedIds, Dictionary<long, HierarchyNode> nodes, Dictionary<long, long> parentOf)
    {
        var childrenOf = new Dictionary<long, List<long>>();
        var rootIds = new List<long>();

        foreach (var fileId in orderedIds)
        {
            if (parentOf.TryGetValue(fileId, out var parentId) && nodes.ContainsKey(parentId))
            {
                if (!childrenOf.TryGetValue(parentId, out var siblings))
                {
                    siblings = [];
                    childrenOf[parentId] = siblings;
                }

                siblings.Add(fileId);
            }
            else
            {
                rootIds.Add(fileId);
            }
        }

        var visited = new HashSet<long>();
        var roots = new List<HierarchyNode>();
        foreach (var rootId in rootIds) roots.Add(Assemble(rootId));

        foreach (var fileId in orderedIds)
        {
            if (!visited.Contains(fileId)) roots.Add(Assemble(fileId));
        }

        return roots;

        HierarchyNode Assemble(long fileId)
        {
            var node = nodes[fileId];
            if (!visited.Add(fileId)) return node;

            var children = childrenOf.TryGetValue(fileId, out var kids)
                ? kids.Select(Assemble).ToList()
                : (IReadOnlyList<HierarchyNode>)[];

            return node with { Children = children };
        }
    }
}
