#!/usr/bin/env bash
#
# Version lockstep gate.
#
#   bash scripts/check-version-lockstep.sh 2.1.0
#
# Every site that carries the shipped version, compared against the version you intend to release.
# Prints a table of site -> found, and exits non-zero if any of them disagrees.
#
# WHY THIS EXISTS. `Documentation/ReleasePipeline.md` section 2 lists these sites, and a table in a
# document is not a gate: `plugin.json` sat at 0.1.0 through the entire 2.0.0 cycle because nothing
# ever compared it to anything. `release.yml` grew a check for that ONE file afterwards. This
# generalises it to every row, and runs before you tag rather than after.
#
# TWO KINDS OF ROW, and conflating them would be a bug:
#
#   - LOCKSTEP sites move with the release. They are compared to the version you pass in.
#   - The UNITY PLUGIN carries its OWN version line (HadesBoot.PluginVersion), deliberately
#     independent of the app's - the app and the plugin ship on different cadences, and the skew
#     between them is itself a feature the code reasons about (PluginVersionSkewTests). It is
#     therefore NEVER compared to the release version. What IS checked is that its test mirrors
#     still agree with it, because those are hand-copied literals that go stale silently.
#
# RELEASE-ONLY ROWS: the installer checksums. They cannot be right before the artifacts exist, so
# they fail this gate until you pin them. That is the intended behaviour - you cannot release
# without them - but it means this gate is red during ordinary development, by design.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

SKIP_CHECKSUMS=0
WANT=""

for arg in "$@"; do
    case "$arg" in
        # For CI at TAG TIME, and for nothing else. The Windows MSIs are built by the tag run
        # itself, and an MSI is not byte-reproducible - each build gets a fresh package code and
        # cab timestamps - so their checksums cannot possibly be pinned before the tag exists.
        # Without this flag the gate and the release flow deadlock: you cannot tag until the
        # checksums are pinned, and you cannot know them until you tag.
        #
        # Run the gate WITHOUT this flag before publishing the release. That is the run that
        # actually holds the checksums to account; see ReleasePipeline.md sections 8.4 and 9.
        --skip-checksums) SKIP_CHECKSUMS=1 ;;
        -*) printf 'error: unknown option %s\n' "$arg" >&2; exit 2 ;;
        *)  WANT="$arg" ;;
    esac
done

if [[ -z "$WANT" ]]; then
    printf 'usage: %s <intended-version> [--skip-checksums]\n\n  e.g. %s 2.1.0\n' "$0" "$0" >&2
    exit 2
fi

if ! [[ "$WANT" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    printf 'error: "%s" is not a three-part version like 2.1.0\n' "$WANT" >&2
    exit 2
fi

FAILURES=0

bold()  { printf '\033[1m%s\033[0m\n' "$*"; }
red()   { printf '\033[1;31m%s\033[0m\n' "$*"; }

# Prints one row. Args: label, file (repo-relative), extracted value, expected value.
# An empty extracted value means the pattern did not match - which is a failure in its own right,
# because a silently-renamed constant would otherwise read as "nothing to check here".
row() {
    local label="$1" file="$2" found="$3" want="$4" status

    if [[ ! -f "${REPO_ROOT}/${file}" ]]; then
        status="MISSING FILE"
    elif [[ -z "$found" ]]; then
        status="NOT FOUND"
        found="-"
    elif [[ "$found" == "$want" ]]; then
        status="ok"
    else
        status="MISMATCH"
    fi

    printf '  %-58s %-22s %s\n' "$label" "$found" "$status"
    [[ "$status" == "ok" ]] || FAILURES=$((FAILURES + 1))
}

# sed against a file that may not exist would print an error per call; callers pass through this.
extract() {
    local file="$1" script="$2"
    [[ -f "${REPO_ROOT}/${file}" ]] || return 0
    sed -n "$script" "${REPO_ROOT}/${file}" | head -1
}

# --------------------------------------------------------------------- lockstep with the release

bold "Version lockstep gate - intended release version ${WANT}"
echo
printf '  %-58s %-22s %s\n' "SITE" "FOUND" "STATUS"
printf '  %-58s %-22s %s\n' "$(printf '%.0s-' {1..58})" "$(printf '%.0s-' {1..22})" "------"

F='Core/src/Hades.Server/Mcp/HadesTools.cs'
row "${F} (ServerVersion)" "$F" \
    "$(extract "$F" 's/.*ServerVersion[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p')" "$WANT"

# The plist is generated by a heredoc inside build-app.sh, so the version lives on the line AFTER
# the key rather than on it. grep -A1 is what makes that reachable from sed.
F='Mac/HadesApp/scripts/build-app.sh'
PLIST_V=''
if [[ -f "${REPO_ROOT}/${F}" ]]; then
    PLIST_V="$(grep -A1 'CFBundleShortVersionString' "${REPO_ROOT}/${F}" \
        | sed -n 's/.*<string>\([^<]*\)<\/string>.*/\1/p' | head -1)"
fi
row "${F} (CFBundleShortVersionString)" "$F" "$PLIST_V" "$WANT"

F='install.sh'
row "${F} (VERSION)" "$F" \
    "$(extract "$F" 's/^VERSION="\([^"]*\)".*/\1/p')" "$WANT"

F='install.ps1'
row "${F} (\$Version)" "$F" \
    "$(extract "$F" "s/^[\$]Version[[:space:]]*=[[:space:]]*'\([^']*\)'.*/\1/p")" "$WANT"

F='ClaudeCodePlugin/.claude-plugin/plugin.json'
row "${F} (version)" "$F" \
    "$(extract "$F" 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')" "$WANT"

# --------------------------------------------------- the Unity plugin's own, independent version

echo
bold "Unity plugin - its own version line, NOT compared to ${WANT}"
echo
printf '  %-58s %-22s %s\n' "SITE" "FOUND" "STATUS"
printf '  %-58s %-22s %s\n' "$(printf '%.0s-' {1..58})" "$(printf '%.0s-' {1..22})" "------"

F='UnityPlugin/Assets/Hades/Runtime/HadesBoot.cs'
PLUGIN_V="$(extract "$F" 's/.*PluginVersion[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p')"
row "${F} (PluginVersion)  <- source of truth" "$F" "$PLUGIN_V" "$PLUGIN_V"

# Hand-copied literals in tests. They pin the real constant on purpose - each carries a comment
# saying so - which makes them exactly the kind of thing that rots without a check.
for F in 'Core/tests/Hades.Server.Tests/CharonStatusTests.cs' \
         'Core/tests/Hades.Server.Tests/Control/ProjectsTests.cs'; do
    row "${F} (RealAppPluginVersion)" "$F" \
        "$(extract "$F" 's/.*RealAppPluginVersion[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p')" "$PLUGIN_V"
done

# ------------------------------------------------------------------- release-only: the checksums

if [[ $SKIP_CHECKSUMS -eq 1 ]]; then
    echo
    bold "Installer checksums - SKIPPED (--skip-checksums)"
    echo
    echo "  Not verified here. Run this again without the flag before publishing the release."
    echo
    if [[ $FAILURES -eq 0 ]]; then
        printf '\033[1;32m%s\033[0m\n' "All version sites agree on ${WANT}. Checksums not checked."
        exit 0
    fi
    red "${FAILURES} site(s) need attention before releasing ${WANT}."
    exit 1
fi

echo
bold "Installer checksums - must be pinned to the PUBLISHED artifacts before release"
echo
printf '  %-58s %-22s %s\n' "SITE" "FOUND" "STATUS"
printf '  %-58s %-22s %s\n' "$(printf '%.0s-' {1..58})" "$(printf '%.0s-' {1..22})" "------"

# Reported as a 12-character prefix: enough to tell "pinned" from "not pinned" and to eyeball a
# change between runs, without a wall of hex in the table.
checksum_row() {
    local label="$1" file="$2" value="$3" status shown

    if [[ ! -f "${REPO_ROOT}/${file}" ]]; then
        status="MISSING FILE"; shown="-"
    elif [[ -z "$value" ]]; then
        status="NOT FOUND"; shown="-"
    elif [[ "$value" == "REPLACE_AT_RELEASE" ]]; then
        status="NOT PINNED"; shown="$value"
    elif [[ "$value" =~ ^[0-9a-fA-F]{64}$ ]]; then
        status="ok"; shown="${value:0:12}..."
    else
        status="NOT A SHA256"; shown="$value"
    fi

    printf '  %-58s %-22s %s\n' "$label" "$shown" "$status"
    [[ "$status" == "ok" ]] || FAILURES=$((FAILURES + 1))
}

F='install.sh'
checksum_row "${F} (SHA256, macOS DMG)" "$F" \
    "$(extract "$F" 's/^SHA256="\([^"]*\)".*/\1/p')"

F='install.ps1'
for RID in win-x64 win-arm64; do
    checksum_row "${F} (\$Sha256['${RID}'])" "$F" \
        "$(extract "$F" "s/.*'${RID}'[[:space:]]*=[[:space:]]*'\([^']*\)'.*/\1/p")"
done

# ------------------------------------------------------------------------------------- verdict

echo
if [[ $FAILURES -eq 0 ]]; then
    printf '\033[1;32m%s\033[0m\n' "All sites agree on ${WANT}."
    exit 0
fi

red "${FAILURES} site(s) need attention before releasing ${WANT}."
cat <<EOF

  Fix every row above that is not 'ok', then run this again. Do not tag until it is green:
  Documentation/ReleasePipeline.md section 2 lists what each site is for.
EOF
exit 1
