import Foundation
import Testing

@testable import HadesControl

// This file decodes Core/tests/Fixtures/control-api/ - the corpus GENERATED by
// FixtureGenerationTests.GenerateTheCorpus from the server's own wire DTOs - and asserts only that
// each fixture decodes into its Swift type without throwing (plus, for the `_absent` fixtures, that
// the field `JsonIgnoreCondition.WhenWritingNull` omits actually decodes as `nil`, not as a thrown
// "missing key" error). It never asserts a literal value: this corpus's data is synthetic exemplar
// data produced by the generator, not a real server response, so a value like a row count or a
// specific string carries no meaning to pin. Semantic content (`callCount == 7`, real productGuids,
// real error text) is exactly what Tests/HadesControlTests/Fixtures/ + DTODecodingTests.swift pin,
// from fixtures hand-captured off a real running Hades.Server - that corpus and this one serve
// different purposes and neither substitutes for the other.
//
// What THIS file proves: the .NET Hades.Control.Client and the Swift HadesControl package agree on
// wire *shape* - property names, casing, and which optional fields are omitted vs. present - because
// both decode the same generated bytes.
//
// The corpus is read directly off disk via an absolute path derived from #filePath, deliberately
// bypassing SwiftPM resources entirely: a prior attempt found SwiftPM's `.copy` resource step
// mangles a symlinked fixtures directory, and this sidesteps that by never declaring the corpus as
// a package resource at all.
@Suite("Generated corpus: wire shape")
struct GeneratedCorpusShapeTests {
    /// Core/tests/Fixtures/control-api, resolved relative to this source file rather than to the
    /// SwiftPM resource bundle. #filePath -> .../Mac/HadesControl/Tests/HadesControlTests/ (this
    /// file's directory) -> Tests -> HadesControl -> Mac -> repo root -> Core/tests/Fixtures/control-api.
    static let corpusDirectory: URL = {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent() // HadesControlTests
            .deletingLastPathComponent() // Tests
            .deletingLastPathComponent() // HadesControl
            .deletingLastPathComponent() // Mac
            .deletingLastPathComponent() // repo root
            .appendingPathComponent("Core/tests/Fixtures/control-api")
    }()

    static func decode<T: Decodable>(_ type: T.Type, _ name: String) throws -> T {
        let url = corpusDirectory.appendingPathComponent("\(name).json")
        guard FileManager.default.fileExists(atPath: url.path) else {
            Issue.record(
                """
                Missing generated fixture \(url.path).
                The .NET generator (FixtureGenerationTests.GenerateTheCorpus in \
                Core/tests/Hades.Control.Client.Tests) must be run first to produce \
                Core/tests/Fixtures/control-api/.
                """
            )
            throw CocoaError(.fileNoSuchFile)
        }
        let data = try Data(contentsOf: url)
        return try JSONDecoder().decode(T.self, from: data)
    }

    @Test("SummaryResult decodes")
    func summaryResult() throws {
        _ = try Self.decode(SummaryResult.self, "summary_result")
    }

    @Test("SummaryResult: absent lease decodes as nil, not a missing-key error")
    func summaryResultAbsentLease() throws {
        let result = try Self.decode(SummaryResult.self, "summary_result_absent")
        #expect(result.lease == nil)
    }

    @Test("ProjectsResult decodes")
    func projectsResult() throws {
        _ = try Self.decode(ProjectsResult.self, "projects_result")
    }

    @Test("EditorsResult decodes")
    func editorsResult() throws {
        _ = try Self.decode(EditorsResult.self, "editors_result")
    }

    @Test("SettingsResult decodes")
    func settingsResult() throws {
        _ = try Self.decode(SettingsResult.self, "settings_result")
    }

    @Test("ActionResult decodes")
    func actionResult() throws {
        _ = try Self.decode(ActionResult.self, "action_result")
    }

    @Test("OperationResult decodes")
    func operationResult() throws {
        _ = try Self.decode(OperationResult.self, "operation_result")
    }

    @Test("OperationResult: absent finishedAtUtc/progress/error/result all decode as nil")
    func operationResultAbsent() throws {
        let result = try Self.decode(OperationResult.self, "operation_result_absent")
        #expect(result.finishedAtUtc == nil)
        #expect(result.progress == nil)
        #expect(result.error == nil)
        #expect(result.result == nil)
    }

    @Test("MemoryResult decodes")
    func memoryResult() throws {
        _ = try Self.decode(MemoryResult.self, "memory_result")
    }

    @Test("TraceDetailResult decodes")
    func traceDetailResult() throws {
        _ = try Self.decode(TraceDetailResult.self, "trace_detail_result")
    }

    @Test("TraceSequencesResult decodes")
    func traceSequencesResult() throws {
        _ = try Self.decode(TraceSequencesResult.self, "trace_sequences_result")
    }
}
