using System.Net;
using System.Net.Sockets;
using System.Security.Cryptography;
using System.Text;
using Hades.Contract.Wire;

namespace Hades.Core.Editors;

/// <summary>
/// The app-side end of the Unity Editor link: a loopback-only TCP listener a Unity Editor plugin
/// dials into. Unity dials out; Unity never listens - no port allocation in the Editor, no
/// firewall prompt, no port collision (see the editor-link plan's architecture section). A
/// domain reload drops the socket and the plugin reconnects - reconnect is the normal path, not
/// error recovery.
///
/// Wire handshake, in order, once a TCP connection is accepted:
///  1. One raw line: the token (see <see cref="Token"/>), exactly as written to the token file
///     this instance was constructed with. Missing, or any mismatch, closes the connection
///     immediately - nothing past this point is ever parsed as JSON.
///  2. One line: the JSON <see cref="Hello"/> handshake payload (not a JSON-RPC envelope - its
///     own top-level shape, per the shared contract).
///  3. From here on, one JSON-RPC message per line - see <see cref="EditorSession"/>, which owns
///     everything past this point.
///
/// A fresh, cryptographically random token is generated on every <see cref="Start"/> and written,
/// together with the actual bound port, to the token file at Unix mode 0600 (see
/// <see cref="EditorConnectionInfo"/>) - the port is an OS-assigned ephemeral one (see
/// <paramref name="port"/> on the constructor), so this file is the only place the plugin can
/// learn which port to dial. Loopback binding alone is not sufficient: any OTHER local process
/// can also reach a loopback port, and this one executes project mutations. The token is what
/// keeps this from being an open door for every process on the machine, not just Unity - the
/// audit's "hub HTTP surface has zero authentication" must not be reproduced here.
/// </summary>
public sealed class EditorListener : IDisposable
{
    // Generous bound on the two raw handshake lines (token, hello) read before any JSON parsing
    // happens - large enough for any real token or hello payload, small enough that a hostile or
    // broken peer sending an endless line with no newline cannot grow this without bound.
    const int MaxHandshakeLineBytes = 8 * 1024;

    readonly string _tokenFilePath;
    readonly EditorRegistry _registry;
    readonly LeaseRegistry? _leases;
    readonly int _requestedPort;

    readonly HashSet<EditorSession> _liveSessions = [];
    readonly Lock _gate = new();

    TcpListener? _listener;
    CancellationTokenSource? _cts;
    Task? _acceptLoop;
    bool _disposed;

    /// <param name="tokenFilePath">Where the auth token is written on every <see cref="Start"/> -
    /// typically <see cref="Storage.AppPaths.EditorTokenFile"/>.</param>
    /// <param name="registry">Where a successful handshake registers, and a disconnect
    /// deregisters, the resulting editor.</param>
    /// <param name="leases">Where a successful registration reconciles this app's believed lease
    /// state against what the plugin actually reports - see <see cref="Register"/> and
    /// <see cref="LeaseRegistry.ReconcileAsync"/> - and where a disconnect clears that belief once
    /// this was still the disconnecting session's own registration (see <see cref="Register"/>'s
    /// <c>Disconnected</c> handler). Optional; null (the default) skips both entirely, same as
    /// every other test in this file that has no need of them.</param>
    /// <param name="port">TCP port to bind, or 0 (the default) to let the OS assign a free one -
    /// the actual bound port is read back via <see cref="Port"/> after <see cref="Start"/>.</param>
    public EditorListener(string tokenFilePath, EditorRegistry registry, LeaseRegistry? leases = null, int port = 0)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(tokenFilePath);
        ArgumentNullException.ThrowIfNull(registry);

        _tokenFilePath = tokenFilePath;
        _registry = registry;
        _leases = leases;
        _requestedPort = port;
    }

    /// <summary>The port actually bound - valid only after <see cref="Start"/>.</summary>
    public int Port { get; private set; }

    /// <summary>The token generated by the most recent <see cref="Start"/>, kept in memory so
    /// callers (tests, a future control API) do not need to re-read the token file.</summary>
    public string Token { get; private set; } = "";

    /// <summary>Generates a fresh token, starts accepting connections on loopback only, and
    /// writes the actual bound port together with the token to the connection file at mode
    /// 0600.</summary>
    public void Start()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        if (_listener is not null) throw new InvalidOperationException("EditorListener is already started.");

        Token = GenerateToken();

        // IPAddress.Loopback (127.0.0.1), never IPAddress.Any: this is the security boundary
        // that keeps the listener unreachable from anywhere but this machine. There is
        // deliberately no way to override this - see the class doc comment.
        _listener = new TcpListener(IPAddress.Loopback, _requestedPort);
        _listener.Start();
        Port = ((IPEndPoint)_listener.LocalEndpoint).Port;

        // Written only now that Port reflects the actual bound port (Start() above resolves the
        // OS-assigned ephemeral port when _requestedPort is 0) - writing it earlier would leak
        // the pre-bind placeholder to a plugin that dials in before this method returns.
        WriteConnectionFile(Token, Port);

        _cts = new CancellationTokenSource();
        _acceptLoop = Task.Run(() => AcceptLoopAsync(_cts.Token));
    }

    async Task AcceptLoopAsync(CancellationToken token)
    {
        while (!token.IsCancellationRequested)
        {
            TcpClient client;
            try
            {
                client = await _listener!.AcceptTcpClientAsync(token).ConfigureAwait(false);
            }
            catch (Exception e) when (e is OperationCanceledException or ObjectDisposedException or SocketException)
            {
                return; // the listener was stopped - normal shutdown, not a fault.
            }

            _ = HandleConnectionAsync(client, token);
        }
    }

    async Task HandleConnectionAsync(TcpClient client, CancellationToken token)
    {
        client.NoDelay = true;
        var stream = client.GetStream();

        try
        {
            var tokenLine = await ReadRawLineAsync(stream, token).ConfigureAwait(false);
            if (tokenLine is null || !TokenMatches(Token, tokenLine))
            {
                client.Close();
                return;
            }

            var helloLine = await ReadRawLineAsync(stream, token).ConfigureAwait(false);
            if (helloLine is null
                || !Hello.TryParse(helloLine, out var hello, out _)
                || hello is null
                || string.IsNullOrEmpty(hello.ProjectGuid))
            {
                client.Close();
                return;
            }

            // Hello.PluginVersion is deliberately never inspected here - not an oversight. Spec #4
            // §6: "degrades rather than refuses... silent refusal on version skew is how the
            // current support burden started." A well-formed Hello with a non-empty ProjectGuid
            // registers regardless of what it reports for PluginVersion - one minor behind, a
            // major version apart in either direction, even empty/unparseable. Version-skew
            // handling (the warning, and offering an in-place update of Assets/Hades/) happens
            // entirely above this transport layer, in ProjectsEndpoint/SummaryTools - see
            // Editors.PluginVersionSkew's own class doc comment, and EditorListenerTests'
            // dedicated proof that the refusal path is not taken.
            Register(client, stream, hello);
        }
        catch (Exception e) when (e is IOException or ObjectDisposedException or SocketException or OperationCanceledException)
        {
            client.Close();
        }
    }

    void Register(TcpClient client, Stream stream, Hello hello)
    {
        var projectGuid = hello.ProjectGuid!;
        var session = new EditorSession(stream, hello);

        lock (_gate)
        {
            if (_disposed)
            {
                // Lost the race with Dispose(): no new registrations past shutdown.
                session.Dispose();
                client.Close();
                return;
            }

            _liveSessions.Add(session);
        }

        // Subscribed before Start() - see EditorSession.Start's doc comment on why that ordering
        // matters: the read loop can observe EOF and raise Disconnected as soon as it runs.
        session.Disconnected += () =>
        {
            // Deregister unconditionally, as always - EditorRegistry.Deregister's own newest-wins
            // guard (see its doc comment) already makes this safe for a stale, superseded
            // session: it only actually removes the registration - and only THEN returns true -
            // when this session is still the current one for projectGuid.
            var wasCurrentRegistration = _registry.Deregister(projectGuid, session);

            // Clear this app's believed-held lease for the project, but ONLY when this session's
            // own deregistration just took effect - i.e. this is not a stale connection belatedly
            // noticing it is dead after a newer Editor already replaced it. A newer connection may
            // already be attached (or reconcile its own lease belief moments from now); this old
            // connection's death must not clobber that belief, exactly the same newest-wins
            // reasoning EditorRegistry.Deregister's own guard exists for. Without this, the app
            // would keep believing a lease is held long after the plugin's own
            // ReloadGate.ReleaseOnDisconnect (plan 8) already freed the real lock - and
            // /control/summary (Plan 11 Task 2) would keep showing a Release button for a lease
            // that no longer exists.
            //
            // Best-effort and never allowed to delay or break the rest of this cleanup below -
            // same fire-and-forget spirit as ReconcileLeaseAsync above, though this is
            // synchronous and in-memory (a Dictionary.Remove under a lock), so it needs no Task.
            if (wasCurrentRegistration && _leases is not null)
            {
                try
                {
                    _leases.Clear(projectGuid);
                }
                catch
                {
                    // Best-effort - see this block's own comment above.
                }
            }

            lock (_gate) { _liveSessions.Remove(session); }
            client.Close();
        };

        _registry.Register(new AttachedEditor { Hello = hello, ConnectedAtUtc = DateTimeOffset.UtcNow, Session = session });

        session.Start();

        // Reconnect reconciliation (see LeaseRegistry's own class doc comment): resynchronise
        // this app's believed lease state against what the plugin actually reports, now that the
        // session can answer requests (Start() just above). Fire-and-forget, deliberately -
        // registration has already happened unconditionally on the lines above, and must not be
        // gated on this succeeding: a plugin that cannot answer (dropped mid-probe, or an older
        // plugin version erroring on lease.renew) must leave the editor attached, not un-register
        // it. See ReconcileLeaseAsync's own doc comment for why its exception handling matters.
        // Same fire-and-forget shape as AcceptLoopAsync's "_ = HandleConnectionAsync(...)" above.
        if (_leases is not null) _ = ReconcileLeaseAsync(projectGuid, session);
    }

    /// <summary>
    /// Best-effort wrapper around <see cref="LeaseRegistry.ReconcileAsync"/> for one just-registered
    /// session - swallows whatever it throws (a dropped connection, a malformed response, or a
    /// real JSON-RPC error from a plugin that does not support <c>lease.renew</c>) rather than
    /// letting it propagate. <see cref="Register"/> has already attached this editor by the time
    /// this runs; an inconclusive reconciliation attempt must never retroactively undo that - the
    /// existing believed lease (if any) is simply left as-is, same as <c>ReconcileAsync</c>'s own
    /// doc comment describes for a propagated exception, and the next successful reconnect gets
    /// another chance.
    /// </summary>
    async Task ReconcileLeaseAsync(string projectGuid, EditorSession session)
    {
        try
        {
            await _leases!.ReconcileAsync(projectGuid, session).ConfigureAwait(false);
        }
        catch
        {
            // Best-effort: see this method's own doc comment for why swallowing is correct here.
        }
    }

    static string GenerateToken() => Convert.ToHexStringLower(RandomNumberGenerator.GetBytes(32));

    void WriteConnectionFile(string token, int port)
    {
        var directory = Path.GetDirectoryName(_tokenFilePath);
        if (!string.IsNullOrEmpty(directory)) Directory.CreateDirectory(directory);

        // Write, then fix the mode unconditionally: FileStreamOptions.UnixCreateMode only applies
        // when a NEW inode is created, so it would silently leave a pre-existing file (a stale
        // token from a previous run, or one some other tool wrote) at whatever mode it already
        // had. Explicitly setting it after the write guarantees the end state is 0600 regardless
        // of what, if anything, was there before - which is what the test asserts.
        var info = new EditorConnectionInfo { Port = port, Token = token };
        File.WriteAllText(_tokenFilePath, MiniJson.Write(info.ToJson()));

        // Hades targets macOS (see the Mac Shell spec); File.SetUnixFileMode is unsupported on
        // Windows. OperatingSystem.IsWindows() is the analyzer-recognised platform-guard pattern,
        // so this stays warning-free without a project-wide platform declaration that would also
        // constrain every other public member of this assembly.
        if (!OperatingSystem.IsWindows())
        {
            File.SetUnixFileMode(_tokenFilePath, UnixFileMode.UserRead | UnixFileMode.UserWrite);
        }
    }

    /// <summary>Constant-time comparison so a mismatched token cannot be brute-forced faster by
    /// timing how quickly this call returns.</summary>
    static bool TokenMatches(string expected, string presented) =>
        CryptographicOperations.FixedTimeEquals(Encoding.UTF8.GetBytes(expected), Encoding.UTF8.GetBytes(presented));

    /// <summary>
    /// Reads one raw, newline-terminated line as UTF-8 text - used only for the two handshake
    /// lines, before any <see cref="EditorSession"/> (and its buffering <see cref="StreamReader"/>)
    /// exists for this connection. Reading byte-by-byte here, rather than wrapping the stream in
    /// a StreamReader early, is deliberate: a StreamReader created now and a second one created
    /// later for EditorSession would fight over the same underlying stream, since the first could
    /// buffer-ahead bytes the second never sees. The handshake is a handful of bytes, so the
    /// per-byte cost is irrelevant. Returns null on EOF before a newline, or on a line longer than
    /// <see cref="MaxHandshakeLineBytes"/> - both are treated identically to "no token" by the
    /// caller.
    /// </summary>
    static async Task<string?> ReadRawLineAsync(Stream stream, CancellationToken cancellationToken)
    {
        using var buffer = new MemoryStream();
        var single = new byte[1];

        while (buffer.Length <= MaxHandshakeLineBytes)
        {
            var read = await stream.ReadAsync(single, cancellationToken).ConfigureAwait(false);
            if (read == 0) return null;
            if (single[0] == (byte)'\n') return Encoding.UTF8.GetString(buffer.ToArray());
            buffer.WriteByte(single[0]);
        }

        return null;
    }

    public void Dispose()
    {
        lock (_gate)
        {
            if (_disposed) return;
            _disposed = true;
        }

        _cts?.Cancel();
        _listener?.Stop();

        List<EditorSession> sessions;
        lock (_gate)
        {
            sessions = [.. _liveSessions];
            _liveSessions.Clear();
        }

        foreach (var session in sessions) session.Dispose();

        _cts?.Dispose();
    }
}
